name: API Services Portal configuration
description: Publishes an api through the gateway
branding:
  icon: message-circle
  color: blue

inputs:
  ### Required
  namespace:
    description: The namespace of you routes collection
    required: true
  client_id:
    description: Namespace's Client ID from API Services Portal
    required: true
  client_secret:
    description: Namespace's Client Secret from API Services Portal
    required: true
  file:
    description: Template file (e.g. frontend/service.gwa.yml)
    required: true

  ### Typical / recommended
  production:
    description: Use production environment (true, default) or test environment (false)
    value: "true"
    
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Publish API
      shell: bash
      run: |
        curl -L -O https://github.com/bcgov/gwa-cli/releases/download/v3.0.7/gwa_Linux_x86_64.tgz
        tar -xvzf gwa_Linux_x86_64.tgz        

        if [ "${{ inputs.production }}" == "false" ]; then
          ./gwa config set host api-gov-bc-ca.test.api.gov.bc.ca
        fi

        ./gwa login \
          --client-id=${{ inputs.client_id }} \
          --client-secret=${{ inputs.client_secret }}
          
        ./gwa config set gateway ${{ inputs.namespace }}

        ./gwa pg ${{ inputs.file }}
