name: API Gateway Deployer
description: API Gateway deployer
branding:
  icon: message-circle
  color: blue

inputs:
  ### Required
  namespace:
    description: The namespace of you routes collection
    required: true
  client_id:
    description: Namespace's Client ID from API Services Portal
    required: true
  client_secret:
    description: Namespace's Client Secret from API Services Portal
    required: true
  file:
    description: Template file (e.g. frontend/service.gwa.yml)
    required: true

  ### Typical / recommended
  production:
    description: Set the environment to be used as the production environment
    value: "true"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Apply API Gateway configuration
      shell: bash
      run: |
        curl -s -L -O https://github.com/bcgov/gwa-cli/releases/download/v2.0.15/gwa_Linux_x86_64.tgz
        tar -xzf gwa_Linux_x86_64.tgz
        export PATH=`pwd`:$PATH
        gwa -v

        gwa config set host api.gov.bc.ca
        if [ "${{ inputs.production }}" == "false" ]; then
          gwa config set host api-gov-bc-ca.test.api.gov.bc.ca
        fi

        gwa config set namespace ${{ inputs.namespace }}
        gwa login \
          --client-id=${{ inputs.client_id }} \
          --client-secret=${{ inputs.client_secret }}

        gwa pg --debug ${{ inputs.file }}
        # gwa apply --debug -i ${{ inputs.file }}
